# Generated by Django 4.1.7 on 2023-08-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='keymap',
            fields=[
                ('keymap_id', models.AutoField(primary_key=True, serialize=False)),
                ('placeholder', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.key')),
            ],
        ),
        migrations.CreateModel(
            name='os',
            fields=[
                ('os_id', models.AutoField(primary_key=True, serialize=False)),
                ('os_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='shortcut',
            fields=[
                ('shortcut_id', models.AutoField(primary_key=True, serialize=False)),
                ('shortcut_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('f_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.os')),
                ('key1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key1', to='API.keymap')),
                ('key2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key2', to='API.keymap')),
                ('key3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key3', to='API.keymap')),
            ],
        ),
    ]
