# Generated by Django 4.1.7 on 2023-08-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymap',
            name='placeholder',
            field=models.IntegerField(),
        ),
    ]
