# Generated by Django 4.1.7 on 2023-08-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_keymap_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymap',
            name='key',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='keymap',
            name='placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
