# Generated by Django 4.1.7 on 2023-08-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_t_user_t_user_unique_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='パスワード'),
        ),
    ]
