# Generated by Django 4.1.7 on 2023-08-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_success_shortcut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='success_shortcut',
            old_name='sucsess_shortcut_id',
            new_name='succsess_shortcut_id',
        ),
    ]
